name: push-master

on:
  push:
    branches:
      - master

jobs:
  Deploy:
    name: Deploy the master branch by @${{ github.actor }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Connect to an EC2 instance and execute scripts
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.USER_NAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd youtube-sharing-be
            git pull
            sudo docker-compose up --build -d
            sudo docker image prune -a -f
            sudo docker builder prune -f
